app:
    resource: '@AppBundle/Controller/'
    type: annotation

groups:
    type:     rest
    resource: AppBundle\Controller\GroupController

users:
    type:     rest
    resource: AppBundle\Controller\UserController
